### ISSUE TITLE
[Elasticsearch JVM] Error opening log file 'logs/gc.log': Permission denied

### ISSUE THREAD

**Issue by AlanPadi95** [AlanPadi95/docker-elastic-stack#1]
### Problem description

Elasticsearch container can't start because a Java error. Java Virtual Machine can't access to the path `logs/gc.log`.

#### Stack configuration

```yml
version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.5.2}
    user: root
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: elastic_logs_config
        target: /usr/share/elasticsearch/config/log4j2.properties
    environment:
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
```
#### Docker setup

```
Docker version 19.03.5, build 633a0ea
```

```
docker-compose version 1.25.0, build 0a186604
```

#### Docker logs

```java
Created elasticsearch keystore in /usr/share/elasticsearch/config
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:
[0.002s][error][logging] Error opening log file 'logs/gc.log': Permission denied
[0.002s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.
error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:118)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:86)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:92)```

**Comment by AlanPadi95** [comment]
## [SOLVED]

This issue has been solved applying the solution of this [web page](https://blog.csdn.net/qq_15256981/article/details/88605824).

To give permissions to the shared volumes to Java Virtual Machine, I add another environment variable to the Elasticsearch service: **- TAKE_FILE_OWNERSHIP=true**. 

Now, the service configuration in the `docker-compose.yml` file is like:

```yml
version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.5.2}
    user: root
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: elastic_logs_config
        target: /usr/share/elasticsearch/config/log4j2.properties
    environment:
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
      - TAKE_FILE_OWNERSHIP=true 
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
```
